#pragma once

#include <stdbool.h>

#define VOICE_NODE_DEVICE_ID CONFIG_VOICE_NODE_DEVICE_ID
#define VOICE_NODE_FIRMWARE_VERSION CONFIG_VOICE_NODE_FIRMWARE_VERSION
#define VOICE_NODE_SERVER_BASE_URL CONFIG_VOICE_NODE_SERVER_BASE_URL
#define VOICE_NODE_HEARTBEAT_INTERVAL_MS CONFIG_VOICE_NODE_HEARTBEAT_INTERVAL_MS

#ifndef CONFIG_VOICE_NODE_MIC_RECORD_GAIN
#define CONFIG_VOICE_NODE_MIC_RECORD_GAIN 32
#endif

#ifndef CONFIG_VOICE_NODE_MIC_VAD_THRESHOLD
#define CONFIG_VOICE_NODE_MIC_VAD_THRESHOLD 40
#endif

#ifndef CONFIG_VOICE_NODE_MIC_VAD_MIN_RECORD_MS
#define CONFIG_VOICE_NODE_MIC_VAD_MIN_RECORD_MS 1500
#endif

#ifndef CONFIG_VOICE_NODE_MIC_VAD_SILENCE_STOP_MS
#define CONFIG_VOICE_NODE_MIC_VAD_SILENCE_STOP_MS 900
#endif

#ifndef CONFIG_VOICE_NODE_AUDIO_UPLOAD_TEST_DELAY_MS
#define CONFIG_VOICE_NODE_AUDIO_UPLOAD_TEST_DELAY_MS 3000
#endif

#ifndef CONFIG_VOICE_NODE_BUTTON_GPIO
#define CONFIG_VOICE_NODE_BUTTON_GPIO 0
#endif

#ifndef CONFIG_VOICE_NODE_BUTTON_DEBOUNCE_MS
#define CONFIG_VOICE_NODE_BUTTON_DEBOUNCE_MS 250
#endif

#ifndef CONFIG_VOICE_NODE_BUTTON_LONG_PRESS_MS
#define CONFIG_VOICE_NODE_BUTTON_LONG_PRESS_MS 2000
#endif

#ifndef CONFIG_VOICE_NODE_SPEAKER_LRC_GPIO
#define CONFIG_VOICE_NODE_SPEAKER_LRC_GPIO 9
#endif

#ifndef CONFIG_VOICE_NODE_SPEAKER_BCLK_GPIO
#define CONFIG_VOICE_NODE_SPEAKER_BCLK_GPIO 10
#endif

#ifndef CONFIG_VOICE_NODE_SPEAKER_DIN_GPIO
#define CONFIG_VOICE_NODE_SPEAKER_DIN_GPIO 11
#endif

#ifndef CONFIG_VOICE_NODE_SPEAKER_SAMPLE_RATE
#define CONFIG_VOICE_NODE_SPEAKER_SAMPLE_RATE 24000
#endif

#ifndef CONFIG_VOICE_NODE_SPEAKER_BEEP_FREQUENCY_HZ
#define CONFIG_VOICE_NODE_SPEAKER_BEEP_FREQUENCY_HZ 880
#endif

#ifndef CONFIG_VOICE_NODE_SPEAKER_BEEP_DURATION_MS
#define CONFIG_VOICE_NODE_SPEAKER_BEEP_DURATION_MS 160
#endif

#ifndef CONFIG_VOICE_NODE_SPEAKER_BEEP_AMPLITUDE
#define CONFIG_VOICE_NODE_SPEAKER_BEEP_AMPLITUDE 5000
#endif

#ifndef CONFIG_VOICE_NODE_SPEAKER_REPLY_VOLUME_PERCENT
#define CONFIG_VOICE_NODE_SPEAKER_REPLY_VOLUME_PERCENT 75
#endif

#ifdef CONFIG_VOICE_NODE_MIC_ENABLED
#define VOICE_NODE_MIC_ENABLED true
#else
#define VOICE_NODE_MIC_ENABLED false
#endif

#ifdef CONFIG_VOICE_NODE_MIC_VAD_ENABLED
#define VOICE_NODE_MIC_VAD_ENABLED true
#else
#define VOICE_NODE_MIC_VAD_ENABLED false
#endif

#ifdef CONFIG_VOICE_NODE_AUDIO_UPLOAD_TEST_ENABLED
#define VOICE_NODE_AUDIO_UPLOAD_TEST_ENABLED true
#else
#define VOICE_NODE_AUDIO_UPLOAD_TEST_ENABLED false
#endif

#ifdef CONFIG_VOICE_NODE_BUTTON_UPLOAD_TEST_ENABLED
#define VOICE_NODE_BUTTON_UPLOAD_TEST_ENABLED true
#else
#define VOICE_NODE_BUTTON_UPLOAD_TEST_ENABLED false
#endif

#ifdef CONFIG_VOICE_NODE_BUTTON_ACTIVE_LOW
#define VOICE_NODE_BUTTON_ACTIVE_LOW true
#else
#define VOICE_NODE_BUTTON_ACTIVE_LOW false
#endif

#ifdef CONFIG_VOICE_NODE_SPEAKER_ENABLED
#define VOICE_NODE_SPEAKER_ENABLED true
#else
#define VOICE_NODE_SPEAKER_ENABLED false
#endif

#ifdef CONFIG_VOICE_NODE_SPEAKER_SELF_TEST_ON_BOOT
#define VOICE_NODE_SPEAKER_SELF_TEST_ON_BOOT true
#else
#define VOICE_NODE_SPEAKER_SELF_TEST_ON_BOOT false
#endif

typedef struct {
    bool enabled;
    char wake_word[32];
    int record_seconds;
    int sample_rate;
    char audio_format[12];
    char reply_audio_format[12];
} voice_node_server_config_t;

static inline voice_node_server_config_t voice_node_default_server_config(void)
{
    voice_node_server_config_t config = {
        .enabled = false,
        .wake_word = "Hi ESP",
        .record_seconds = 4,
        .sample_rate = 16000,
        .audio_format = "wav",
        .reply_audio_format = "mp3",
    };
    return config;
}
